version: '3.8'
services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=caching_sha2_password
    volumes:
      - ./mysql:/var/lib/mysql
      - ./travelbudget/init:/docker-entrypoint-initdb.d/:ro
    env_file:
      - ./.env.dev
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    ports:
      - 3307:3306
  web:
    container_name: django-web
    build: 
      context: ./travelbudget
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./travelbudget/:/usr/src/travelbudget/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db