# Generated by Django 3.2.20 on 2023-10-11 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_cost', models.IntegerField()),
                ('hotel_cost', models.IntegerField()),
                ('food_cost', models.IntegerField()),
                ('fun_cost', models.IntegerField()),
                ('travel_cost', models.IntegerField()),
                ('visa_cost', models.IntegerField()),
                ('vaccine_cost', models.IntegerField()),
                ('other_cost', models.IntegerField()),
            ],
            options={
                'db_table': 'cost_table',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'country_table',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='trips.country')),
                ('origin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='trips.country')),
            ],
            options={
                'db_table': 'flight_table',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.IntegerField()),
                ('number_of_travellers', models.IntegerField()),
                ('trip_name', models.CharField(max_length=64)),
                ('reverse', models.BooleanField(default=True)),
                ('cost_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='trips.cost')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='trips.flight')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trip_table',
            },
        ),
    ]
