# Generated by Django 3.2.20 on 2023-10-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('origin', 'destination')},
        ),
    ]
